"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
const workshopOptions=[{value:"private",label:"Private Workshop",detail:"Single guest",guests:"1"},{value:"couples",label:"Couples Workshop",detail:"Two people",guests:"2"},{value:"group",label:"Group Workshop",detail:"5–10 people",guests:"5"}];
const timeWindows=["Morning","Afternoon","Evening","Flexible"];
const inputClass="w-full border-b border-brand-olive/35 bg-transparent px-0 py-3 text-sm text-brand-olive outline-none transition placeholder:text-brand-olive/45 focus:border-brand-maroon";
const labelClass="experience-booking__label";
type BookingFormState={workshop:string;guests:string;preferredDate:string;preferredTime:string;name:string;email:string;phone:string;occasion:string;notes:string};
const initialState:BookingFormState={workshop:"private",guests:"1",preferredDate:"",preferredTime:"Afternoon",name:"",email:"",phone:"",occasion:"",notes:""};
export function WorkshopBookingForm(){const[form,setForm]=useState(initialState);const[submitted,setSubmitted]=useState(false);useEffect(()=>{const params=new URLSearchParams(window.location.search);const selected=params.get("workshop");const match=workshopOptions.find(o=>o.value===selected);if(match)setForm(c=>({...c,workshop:match.value,guests:match.guests}))},[]);const selectedWorkshop=useMemo(()=>workshopOptions.find(o=>o.value===form.workshop)??workshopOptions[0],[form.workshop]);function updateField(field:keyof BookingFormState,value:string){setSubmitted(false);if(field==="workshop"){const match=workshopOptions.find(o=>o.value===value);setForm(c=>({...c,workshop:value,guests:match?.guests??c.guests}));return}setForm(c=>({...c,[field]:value}))}function handleSubmit(event:FormEvent<HTMLFormElement>){event.preventDefault();setSubmitted(true);const subject=`Workshop Booking Request — ${selectedWorkshop.label}`;const body=["New workshop booking request:","",`Workshop: ${selectedWorkshop.label}`,`Guest count: ${form.guests}`,`Preferred date: ${form.preferredDate}`,`Preferred time: ${form.preferredTime}`,`Name: ${form.name}`,`Email: ${form.email}`,`Phone: ${form.phone}`,`Occasion: ${form.occasion||"Not provided"}`,"","Notes:",form.notes||"Not provided"].join("\n");window.location.href=`mailto:contact@elore.design?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`}
return <section id="workshop-booking" className="experience-booking"><div className="editorial-container experience-booking__inner"><aside className="experience-booking__intro"><h2 className="serif-display">Request a workshop date.</h2><p>Choose a workshop format, share your preferred date, and the atelier will confirm availability before finalizing the booking.</p><div className="experience-booking__selection"><p className="serif-display">{selectedWorkshop.label}</p><span>{selectedWorkshop.detail}</span></div></aside>
<form onSubmit={handleSubmit} className="experience-booking__form"><div className="experience-booking__row"><label><span className={labelClass}>Workshop Type</span><select required value={form.workshop} onChange={e=>updateField("workshop",e.target.value)} className={inputClass}>{workshopOptions.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></label><label><span className={labelClass}>Number of Guests</span><input required type="number" min={form.workshop==="group"?5:1} max={form.workshop==="group"?10:form.workshop==="couples"?2:1} value={form.guests} onChange={e=>updateField("guests",e.target.value)} className={inputClass}/></label></div><div className="experience-booking__row"><label><span className={labelClass}>Preferred Date</span><input required type="date" value={form.preferredDate} onChange={e=>updateField("preferredDate",e.target.value)} className={inputClass}/></label><label><span className={labelClass}>Preferred Time</span><select required value={form.preferredTime} onChange={e=>updateField("preferredTime",e.target.value)} className={inputClass}>{timeWindows.map(t=><option key={t}>{t}</option>)}</select></label></div><div className="experience-booking__row"><label><span className={labelClass}>Full Name</span><input required value={form.name} onChange={e=>updateField("name",e.target.value)} placeholder="Your name" className={inputClass}/></label><label><span className={labelClass}>Email Address</span><input required type="email" value={form.email} onChange={e=>updateField("email",e.target.value)} placeholder="you@example.com" className={inputClass}/></label></div><div className="experience-booking__row"><label><span className={labelClass}>Phone Number</span><input required type="tel" value={form.phone} onChange={e=>updateField("phone",e.target.value)} placeholder="(000) 000-0000" className={inputClass}/></label><label><span className={labelClass}>Occasion</span><input value={form.occasion} onChange={e=>updateField("occasion",e.target.value)} placeholder="Birthday, date, team outing..." className={inputClass}/></label></div><label className="experience-booking__notes"><span className={labelClass}>Workshop Notes</span><textarea value={form.notes} onChange={e=>updateField("notes",e.target.value)} placeholder="Share anything helpful about the date, group, materials, or custom direction." rows={5} className={inputClass}/></label><div className="experience-booking__submit"><p>Booking requests are reviewed by the atelier before confirmation.</p><button type="submit" className="btn-olive">Request Booking</button></div>{submitted?<p className="experience-booking__sent">Your email app should open with the workshop request ready to send to contact@elore.design.</p>:null}</form></div></section>}
