import type { Metadata } from "next";
import { PolicyPage } from "@/components/policy-page";
export const metadata: Metadata = { title: "Privacy Policy | ELÖRE Atelier", description: "How ELÖRE Atelier collects, uses, protects, and manages personal information and Google Calendar data." };
export default function PrivacyPolicyPage() {
 return <PolicyPage title="Privacy Policy" updated="September 10, 2026">
 <section className="space-y-5"><p>Elöre Atelier (“Elöre,” “we,” “us,” or “our”) respects your privacy and is committed to protecting the personal information you provide when visiting or making a purchase through our website.</p><p>This Privacy Policy explains what information we collect, how we use it, and the choices available to you when you visit or otherwise interact with Elöre Atelier.</p></section>
 <section className="space-y-4"><h2>SECTION 1 — INFORMATION WE COLLECT</h2><p>When you visit our website, place an order, submit an inquiry, or otherwise interact with our services, we may collect information that you voluntarily provide, including:</p><ul><li>Name</li><li>Email address</li><li>Billing and shipping address</li><li>Phone number</li><li>Order and purchase information</li><li>Hat sizing and customization details</li><li>Information submitted through contact, custom-order, or workshop forms</li><li>Any other information you choose to provide when communicating with us</li></ul><p>When you browse our website, certain information may also be collected automatically, including your IP address, browser type, device information, operating system, and information about how you interact with our website.</p></section>
<section className="space-y-4"><h2>SECTION 2 — HOW WE USE YOUR INFORMATION</h2><p>We use the information we collect to:</p><ul><li>Process and fulfill orders</li><li>Communicate with you about your order, custom requests, or inquiries</li><li>Arrange shipping and delivery</li><li>Process returns and exchanges</li><li>Provide customer service</li><li>Assist with custom hat sizing, design, and modifications</li><li>Manage workshop and experience inquiries</li><li>Improve our website, products, and customer experience</li><li>Send marketing communications when you have chosen to receive them</li><li>Maintain the security and functionality of our website</li><li>Comply with applicable legal obligations</li></ul><p>We only collect and use information that is reasonably necessary for these purposes.</p></section>
<section className="space-y-4"><h2>SECTION 3 — EMAIL MARKETING</h2><p>If you choose to subscribe to Elöre communications, we may use your email address to send you information about new collections, atelier updates, experiences, events, and other brand news.</p><p>You may unsubscribe from marketing communications at any time by following the unsubscribe instructions included in our emails or by contacting us directly.</p><p>Your decision to unsubscribe from marketing communications will not affect transactional communications related to an existing order or inquiry.</p></section>
<section className="space-y-4"><h2>SECTION 4 — CONSENT</h2><p>When you provide personal information to complete a purchase, submit an inquiry, request a custom order, or arrange for delivery or a return, you consent to our collecting and using that information for the specific purpose for which it was provided.</p><p>Where required, we will request your consent before using your information for additional purposes, such as marketing communications.</p><p>You may withdraw your consent to receive marketing communications at any time by contacting us at: <a href="mailto:Salome@elore.atelier">Salome@elore.atelier</a>.</p><p>Please note that withdrawing consent does not affect information that we are required or permitted to retain for legal, transactional, or legitimate business purposes.</p></section>
<section className="space-y-4"><h2>SECTION 5 — SHOPIFY</h2><p>Our online store is hosted on <strong>Shopify</strong>, which provides the e-commerce platform that allows us to sell our products and services to you.</p><p>When you make a purchase through our website, Shopify may collect and process information necessary to complete your transaction, including payment, billing, shipping, and order information.</p><p>Your information may be stored and processed through Shopify&apos;s systems and may be subject to Shopify&apos;s own privacy practices.</p><p>You can learn more about how Shopify handles personal information through its privacy policy.</p></section>
<section className="space-y-4"><h2>SECTION 6 — PAYMENT INFORMATION</h2><p>Payments made through our website are processed through Shopify and/or third-party payment providers. Elöre does not directly store your complete payment card information on our own systems. Payment information is handled by the applicable payment processor in accordance with its security and privacy practices. We encourage you to review the privacy policies of the payment providers used during checkout for additional information about how your payment information is handled.</p></section>
<section className="space-y-4"><h2>SECTION 7 — THIRD-PARTY SERVICES</h2><p>We may work with trusted third-party service providers that assist us with operating our website and business, including:</p><ul><li>Payment processing</li><li>Website hosting and functionality</li><li>Shipping and delivery</li><li>Email communications</li><li>Analytics</li><li>Customer service</li><li>Marketing</li></ul><p>These providers may have access to personal information only to the extent reasonably necessary to perform services on our behalf. Third-party providers may have their own privacy policies governing how they collect, use, and disclose information. We encourage you to review those policies when interacting with their services.</p></section>
<section className="space-y-4"><h2>SECTION 8 — COOKIES</h2><p>Our website may use cookies and similar technologies to provide essential website functionality, remember preferences, understand website traffic, and improve your experience. Cookies may be used for purposes such as:</p><ul><li>Maintaining shopping cart information</li><li>Remembering website sessions</li><li>Understanding how visitors use our website</li><li>Measuring website performance</li><li>Supporting marketing or analytics activities, where applicable</li></ul><p>You may be able to manage or disable cookies through your browser settings. Disabling certain cookies may affect the functionality of portions of the website.</p></section>
<section className="space-y-4"><h2>SECTION 9 — INFORMATION SHARING & DISCLOSURE</h2><p>Elöre does not sell your personal information. We may share personal information with service providers and partners when necessary to operate our business, process your order, provide requested services, or fulfill another purpose described in this Privacy Policy.</p><p>We may also disclose information when required by law, legal process, court order, or governmental request, or when reasonably necessary to protect the rights, property, or safety of Elöre Atelier, our customers, or others.</p></section>
<section className="space-y-4"><h2>SECTION 10 — DATA SECURITY</h2><p>We take reasonable measures to protect personal information against unauthorized access, loss, misuse, alteration, or disclosure. However, no method of transmitting or storing information electronically is completely secure. While we take reasonable precautions to protect your information, we cannot guarantee absolute security.</p></section>
<section className="space-y-4"><h2>SECTION 11 — THIRD-PARTY LINKS</h2><p>Our website may contain links to third-party websites, including social media platforms, collaborators, or other external resources. Once you leave the Elöre website, your activity may be governed by the privacy policies and terms of those third parties. Elöre is not responsible for the privacy practices or content of external websites.</p></section>
<section className="space-y-4"><h2>SECTION 12 — DATA RETENTION</h2><p>We retain personal information only for as long as reasonably necessary to fulfill the purposes for which it was collected, including completing transactions, providing services, maintaining business and financial records, resolving disputes, and complying with legal obligations. When information is no longer reasonably required, we may securely delete or otherwise dispose of it.</p></section>
<section className="space-y-4"><h2>SECTION 13 — YOUR PRIVACY RIGHTS</h2><p>Depending on where you live, you may have certain rights regarding your personal information, including the right to request access to, correction of, or deletion of your information.</p><p>To make a privacy-related request, please contact us at: <a href="mailto:salome@elore.design">salome@elore.design</a>.</p><p>We may need to verify your request before completing it.</p></section>
<section className="space-y-4"><h2>SECTION 14 — GOOGLE CALENDAR & BOOKING DATA</h2><p>Elöre uses Google Calendar to support appointment and workshop scheduling. Our booking system may access the Elöre Atelier booking calendar to check availability, prevent scheduling conflicts, create and manage appointment or workshop events, and send calendar invitations related to confirmed bookings.</p><p>Google Calendar access is authorized through Elöre Atelier&apos;s own booking account. Customers are not required to connect or authorize their personal Google accounts in order to submit a booking request.</p><p>Information used in calendar events may include details reasonably necessary to administer a booking, such as a customer&apos;s name, email address, appointment or workshop type, selected date and time, and relevant booking details. We use Google Calendar data only to provide and operate these scheduling features. Elöre does not sell Google user data or use Google Calendar data for advertising.</p><p>Google user data accessed through Google APIs is handled in accordance with this Privacy Policy and applicable Google API Services User Data requirements.</p></section>
<section className="space-y-4"><h2>SECTION 15 — CHANGES TO THIS PRIVACY POLICY</h2><p>Elöre Atelier may update this Privacy Policy from time to time to reflect changes to our practices, services, or legal requirements. When we make changes, we will update the “Last Updated” date at the top of this policy. We encourage you to review this page periodically. Your continued use of our website following the posting of changes constitutes your acknowledgment of the updated Privacy Policy.</p></section>
<section className="space-y-4"><h2>SECTION 16 — CONTACT US</h2><p>If you have questions about this Privacy Policy, how your information is handled, or would like to make a privacy-related request, please contact:<br/><strong>Elöre Atelier</strong><br/><a href="mailto:Salome@elore.atelier">Salome@elore.atelier</a></p></section>
 </PolicyPage>;
}
