"use client";
import Image from "next/image";
import {useRouter} from "next/navigation";
import {Product} from "@/lib/shopify/types";
import {AddFeedbackButton} from "@/components/shop/add-feedback-button";
import {WishlistButton} from "@/components/wishlist/wishlist-button";
export function ProductCard({product,index}:{product:Product;index:number}){const router=useRouter();const unavailable=product.availableForSale===false;return <article role="link" tabIndex={0} onClick={()=>router.push(`/shop/${product.handle}`)} onKeyDown={e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();router.push(`/shop/${product.handle}`)}}} className="group cursor-pointer" aria-label={`View ${product.title}`}>
 <div className={`relative overflow-hidden bg-[#eee7dc] ${index%5===0?"aspect-[4/5]":index%5===1?"aspect-[3/4]":"aspect-[2477/1651]"}`}><Image src={product.image} alt={product.title} fill sizes="(max-width:640px) 100vw,(max-width:1280px) 50vw,45vw" className="object-cover transition duration-700 group-hover:scale-[1.025]"/><div className="absolute right-3 top-3 z-20"><WishlistButton handle={product.handle} compact/></div>{unavailable?<div className="absolute left-3 top-3 bg-brand-bone px-3 py-2 text-[10px] uppercase tracking-[.22em] text-brand-olive">Unavailable</div>:null}<div className="absolute inset-x-3 bottom-3 z-20 hidden opacity-0 transition group-hover:opacity-100 md:block"><AddFeedbackButton product={product} compact/></div></div>
 <div className="border-b border-brand-olive/25 py-5"><p className="text-[9px] uppercase tracking-[.24em] text-brand-maroon sm:text-[10px]">{product.category}</p><div className="mt-2 flex items-start justify-between gap-4"><h3 className="serif-display text-3xl leading-[.95] text-brand-olive md:text-4xl">{product.title}</h3><span className="shrink-0 text-sm text-brand-olive">{product.price}</span></div><p className="mt-3 hidden max-w-xl text-sm leading-7 text-brand-olive/70 sm:block">{product.description}</p><div className="mt-4 md:hidden"><AddFeedbackButton product={product} compact/></div></div>
 </article>}
