import type { Metadata } from "next";
import { PolicyPage } from "@/components/policy-page";
export const metadata: Metadata = { title: "Terms of Service | ELÖRE Atelier", description: "Terms governing use of the ELÖRE Atelier website and purchases of products and services." };
export default function TermsPage() {
 return <PolicyPage title="Terms of Service" updated="September 10, 2026">
 <section className="space-y-5"><p>Welcome to Elöre Atelier. These Terms of Service govern your use of the Elöre Atelier website and your purchase of products and services through our site. By accessing or using our website, you agree to be bound by these terms.</p></section>
 <section className="space-y-4"><h2>SECTION 1 — USE OF OUR WEBSITE</h2><p>By using this website, you confirm that you are of legal age in your jurisdiction to enter into these terms, or that you have permission from a parent or legal guardian to use the site.</p><p>You agree to use our website only for lawful purposes and not to misuse, disrupt, or interfere with the website, its content, or its functionality.</p></section>
<section className="space-y-4"><h2>SECTION 2 — PRODUCTS & CRAFTSMANSHIP</h2><p>Elöre Atelier creates handcrafted hats and accessories using carefully selected materials and traditional hat-making techniques.</p><p>Because each piece is made by hand, natural variations in color, texture, shape, and finish may occur. These variations are not considered defects but are part of the character and individuality of a handcrafted piece.</p><p>We make every effort to accurately display our products, including their colors, materials, and details. However, colors may appear differently depending on your device or screen.</p></section>
<section className="space-y-4"><h2>SECTION 3 — ORDERS & MADE-TO-ORDER PRODUCTS</h2><p>Many Elöre pieces are made to order and crafted specifically for each customer. By placing an order, you acknowledge that production requires time and that your piece may take approximately <strong>10–25 days from receipt of the order</strong> to be completed, depending on the materials required and the location of shipment.</p><p>Because materials may be uniquely sourced from artisans around the world, production timelines may vary.</p><p>Once an order has been transmitted to the atelier, <strong>modifications may be requested within 72 hours</strong>. Depending on the request, we may be able to accommodate adjustments to sizing, design, trim, tailoring, or other details.</p><p>Requests received after this 72-hour window may not be able to be accommodated once production has begun.</p></section>
<section className="space-y-4"><h2>SECTION 4 — CUSTOM ORDERS</h2><p>Custom orders are individually designed and created for the customer. Once a custom order or modification has been approved and production has begun, it is considered <strong>final sale</strong> and cannot be returned or exchanged.</p><p>We encourage customers to communicate any questions regarding sizing, design, materials, or other details before production begins.</p></section>
<section className="space-y-4"><h2>SECTION 5 — PRICING & PAYMENT</h2><p>All prices displayed on the website are listed in U.S. dollars unless otherwise stated.</p><p>Elöre reserves the right to change product pricing, availability, and descriptions at any time without prior notice. Any price change will not affect an order that has already been confirmed.</p><p>Payment must be received before an order enters production unless otherwise agreed upon in writing.</p></section>
<section className="space-y-4"><h2>SECTION 6 — RETURNS & EXCHANGES</h2><p>Elöre accepts eligible returns and exchanges within <strong>14 days of delivery</strong>. Please refer to our <a href="/refund-policy">Refund &amp; Exchange Policy</a> for complete details regarding eligibility, return conditions, and custom orders.</p><p>Elöre covers return shipping costs within the US and for eligible returns.</p></section>
<section className="space-y-4"><h2>SECTION 7 — SHIPPING</h2><p>Elöre currently ships within the <strong>United States and Europe.</strong></p><p>Once an order has shipped, delivery times may vary depending on the shipping carrier and destination. Elöre is not responsible for delays caused by circumstances outside of our control, including carrier delays, weather, or other unforeseen circumstances.</p></section>
<section className="space-y-4"><h2>SECTION 8 — INTELLECTUAL PROPERTY</h2><p>All content on the Elöre Atelier website—including photographs, product imagery, written content, logos, graphics, designs, trademarks, and other materials—is the property of Elöre Atelier or its respective creators and is protected by applicable intellectual property laws.</p><p>You may not reproduce, distribute, modify, publish, or use our content for commercial purposes without prior written permission.</p></section>
<section className="space-y-4"><h2>SECTION 9 — THIRD-PARTY SERVICES & LINKS</h2><p>Our website may contain links to third-party websites or use third-party services, including payment processing, shipping, analytics, or other website functionality.</p><p>Elöre is not responsible for the content, policies, or practices of third-party websites or services. Your use of those services may be subject to their own terms and policies.</p></section>
<section className="space-y-4"><h2>SECTION 10 — ACCURACY OF INFORMATION</h2><p>We strive to ensure that all information presented on our website is accurate and up to date. However, occasional errors, omissions, or inaccuracies may occur.</p><p>Elöre reserves the right to correct errors, update information, or cancel an order if information displayed on the website was incorrect, including pricing or availability.</p></section>
<section className="space-y-4"><h2>SECTION 11 — CHANGES TO THESE TERMS</h2><p>Elöre Atelier reserves the right to update or modify these Terms of Service at any time. Changes will become effective when posted to this website.</p><p>Your continued use of the website following any changes constitutes acceptance of the updated terms.</p></section>
<section className="space-y-4"><h2>SECTION 12 — CONTACT</h2><p>If you have questions about these Terms of Service, your order, or any of our policies, please contact:<br/><strong>Elöre Atelier | Salome Kopasz</strong><br/><a href="mailto:Salome@elore.atelier">Salome@elore.atelier</a></p></section>
 </PolicyPage>;
}
