import crypto from "crypto";
const ID=process.env.GOOGLE_CALENDAR_ID||"bookingelore@gmail.com";
async function tok(){const b=new URLSearchParams({client_id:process.env.GOOGLE_CLIENT_ID||"",client_secret:process.env.GOOGLE_CLIENT_SECRET||"",refresh_token:process.env.GOOGLE_REFRESH_TOKEN||"",grant_type:"refresh_token"});const r=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:b,cache:"no-store"});if(!r.ok)throw new Error("Calendar authorization failed");return(await r.json()).access_token}
async function api(path:string,init:RequestInit={}){const r=await fetch("https://www.googleapis.com/calendar/v3"+path,{...init,headers:{Authorization:"Bearer "+await tok(),"Content-Type":"application/json"},cache:"no-store"});if(!r.ok)throw new Error("Calendar request failed");return r.status===204?null:r.json()}
export async function available(start:string,end:string){const x=await api("/freeBusy",{method:"POST",body:JSON.stringify({timeMin:start,timeMax:end,timeZone:"America/New_York",items:[{id:ID}]})});return(x.calendars?.[ID]?.busy||[]).length===0}
export async function hold(summary:string,start:string,end:string,description:string){return api("/calendars/"+encodeURIComponent(ID)+"/events",{method:"POST",body:JSON.stringify({summary:"PENDING — "+summary,description,start:{dateTime:start,timeZone:"America/New_York"},end:{dateTime:end,timeZone:"America/New_York"},status:"tentative",transparency:"opaque"})})}
export async function confirm(id:string,email:string,summary:string){const e=await api("/calendars/"+encodeURIComponent(ID)+"/events/"+encodeURIComponent(id));e.summary=summary;e.status="confirmed";e.attendees=[{email}];return api("/calendars/"+encodeURIComponent(ID)+"/events/"+encodeURIComponent(id)+"?sendUpdates=all",{method:"PUT",body:JSON.stringify(e)})}
export async function remove(id:string){return api("/calendars/"+encodeURIComponent(ID)+"/events/"+encodeURIComponent(id),{method:"DELETE"})}
export function sign(data:object){const p=Buffer.from(JSON.stringify({...data,exp:Date.now()+604800000})).toString("base64url");return p+"."+crypto.createHmac("sha256",process.env.BOOKING_ACTION_SECRET||"").update(p).digest("base64url")}
export function verify(t:string){const[p,s]=t.split(".");const x=crypto.createHmac("sha256",process.env.BOOKING_ACTION_SECRET||"").update(p).digest("base64url");if(!p||!s||s!==x)throw 0;const d=JSON.parse(Buffer.from(p,"base64url").toString());if(Date.now()>d.exp)throw 0;return d}